Index/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='Index'
urlpatterns = [
 	url(r'^addcamera/',views.AddcameraView.as_view(), name='addcamera'),
 	url(r'^video_streamer/(?P<camID>\d+)',views.video_streamer, name='video_streamer'),
    url(r'^video_streamer1/',views.video_streamer1, name='video_streamer1'),
 	url(r'^cameras/',views.cameras_list, name='cameras_list'),
 	url(r'^deletecamera/',views.deletecamera, name='deletecamera'),
    url(r'^notification/',views.notification, name='notification'),
    url(r'^image/',views.image, name='image'),
    url(r'^cameradetails/',views.cameradetails, name='cameradetails'),
    url(r'^profile/',views.ProfileView.as_view(), name='profile'),
    url(r'^profile1/',views.ProfileView1.as_view(), name='profile1'),
    url(r'^profiledetail/(?P<pk>\d+)/$',views.ProfileDetailView.as_view(), name='profiledetail'),
    url(r'^profileupdate/(?P<pk>\d+)/$',views.ProfileUpdateView.as_view(), name='profileupdate'),
    # url(r'^jump/',views.jump, name='jump'),
    #url(r'^sample/',views.sample11, name='sample11'),
    url(r'^home/',views.home, name='home'),
    url(r'^preview/',views.preview, name='preview'),

    # AddcameraView.as_view()

 ]# + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from Index.views import (AddcameraView, LiveView)

urlpatterns = [
    url('admin/', admin.site.urls),
    url('api/v1/', include('Index.api_urls')),
    url(r'', include('Index.urls')),
    url(r'', include('faces.urls')),
    url('accounts/', include('django.contrib.auth.urls')),
    url('', TemplateView.as_view(template_name='home.html'), name='home'),#registration/login.html
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
'''
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Index.urls')),
]
'''

Index/templates/Index/Camera_Add.html
{% extends "base.html" %}
{% block location %}
{% if user.is_authenticated %}
{% load static %}

<div class="col-lg-6">
    <div class="card">
      <div class="card-header">Add Camera</div>
          <div class="card-body card-block">
               <form action="#" method="POST" class="">
                 {% csrf_token %}
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-user"></i>
                                  </div>
                                      <input type="text" id="name" name="name" placeholder="Camera Name" class="form-control" required>
                                  </div>
                    </div>
                    <div class="form-group">
                            <div class="input-group">
                              <div class="input-group-addon">
                                  <i class="fa fa-camera"></i>
                                    </div>
                                  <input type="text" id="ip" name="ip" placeholder="Camera URL" class="form-control" required>
                          </div>
                    </div>
                    <div class="form-actions form-group">
                      <button type="submit" class="btn btn-success btn-lg btn-block">Preview</button>
                  </div>
                    {% if questions == None %}
                    <div class="row">
                       <div class="col-lg-6">
                         <section class="card">
                          <div class="card-body text-secondary"><img src="{% static 'images/no-preview-available.png' %}" height="700" width="700"/></div>
                        </section>
                          </div>
                    </div>
                    {% else %}
                    <div class="row">
                       <div class="col-lg-6">
                         <section class="card">
                          <div class="card-body text-secondary"><img src="{% url 'Index:video_streamer1' %}" height="700" width="700"/></div>
                        </section>
                          </div>
                    </div>
                    {% endif %}
                    <!-- <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-user"></i>
                                  </div>
                                      <input type="text" id="auth_uname" name="auth_uname" placeholder="username" class="form-control" required>
                                  </div>
                    </div> -->
                          <!-- <div class="form-group">
                              <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-asterisk"></i>
                            </div>
                          <input type="password" id="auth_pwd" name="auth_pwd" placeholder="Password" class="form-control" required>
                          </div>
                      </div> -->
                      <div class="form-actions form-group">
                        <button type="submit" class="btn btn-success btn-sm">Submit</button>
                    </div>

                    <a class="btn btn-warning btn-lg btn-block" href="{% url 'Index:preview' %}">preview</a>

                </form>


          </div>
      </div>
                    </div>



  <!-- Main -->
  <!-- Copyright -->
{% else %}

      <li><a href="{% url 'Index:profile' %}" >register</a></li>
      <li><a href="{% url 'login' %}" >login</a></li>

{% endif %}
{% endblock %}

Index/templates/Index/camera_delete.html
{% extends "base.html" %}
{% block location %}
{% if user.is_authenticated %}
</script>
<div class="col-lg-6">
  <div class="card">
      <div class="card-header">
        <strong>DeleteCamera</strong>
    </div>
    <div class="card-body card-block">
        <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
          {% csrf_token %}
            <div class="row form-group">
                <div class="col col-md-3">
                    <label for="select" class=" form-control-label">Select</label>
                </div>
                <div class="col-12 col-md-9">
                    <select name="name1" id="select" class="form-control">
                        <option value="0">Please select</option>
                          {% for location in locations %}
                           <option value="{{ location.pk }}">{{ location.name }}</option>
                               {% endfor %}
                    </select>
                </div>
            </div>
       </div>
       <div class="card-footer">
        <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-dot-circle-o"></i> Submit</button>
        <button type="reset" class="btn btn-danger btn-sm"><i class="fa fa-ban"></i> Reset</button>
    </form>
    </div>

 </div>
</div>






  <!-- Copyright -->

{% else %}

      <li><a href="{% url 'login' %}" >Continue</a></li>

{% endif %}
{% endblock %}

Index/templates/Index/cameradetail.html
{% extends "base.html" %}
{% block location %}
{% if user.is_authenticated %}
<div class="col-lg-9">
    <div class="card">
      <!-- <div class="card-header">Add Camera</div> -->
          <div class="card-body card-block">
            <div class="row">
                            <div class="col-md-12">
                                <!-- DATA TABLE -->
                                <center><h3 class="title-5 m-b-35">Camera details</h3></center>
                                <!-- <div class="table-data__tool"> -->
                                    <!-- <div class="table-data__tool-left">
                                        <div class="rs-select2--light rs-select2--md">
                                            <select class="js-select2" name="property">
                                                <option selected="selected">All Properties</option>
                                                <option value="">Option 1</option>
                                                <option value="">Option 2</option>
                                            </select>
                                            <div class="dropDownSelect2"></div>
                                        </div>
                                        <div class="rs-select2--light rs-select2--sm">
                                            <select class="js-select2" name="time">
                                                <option selected="selected">Today</option>
                                                <option value="">3 Days</option>
                                                <option value="">1 Week</option>
                                            </select>
                                            <div class="dropDownSelect2"></div>
                                        </div>
                                        <button class="au-btn-filter">
                                            <i class="zmdi zmdi-filter-list"></i>filters</button>
                                    </div> -->
                                    <!-- <div class="table-data__tool-right">
                                        <button class="au-btn au-btn-icon au-btn--green au-btn--small">
                                            <i class="zmdi zmdi-plus"></i>add item</button>
                                        <div class="rs-select2--dark rs-select2--sm rs-select2--dark2">
                                            <select class="js-select2" name="type">
                                                <option selected="selected">Export</option>
                                                <option value="">Option 1</option>
                                                <option value="">Option 2</option>
                                            </select>
                                            <div class="dropDownSelect2"></div>
                                        </div>
                                    </div> -->
                                <!-- </div> -->
                                <div class="table-responsive table-responsive-data2">
                                    <table class="table table-data2">
                                        <thead>
                                            <tr>
                                                <th>
                                                    <label class="au-checkbox">
                                                        <input type="checkbox">
                                                        <span class="au-checkmark"></span>
                                                    </label>
                                                </th>
                                                <th>name</th>
                                                <th>ip</th>
                                                <!-- <th>username</th>
                                                <th>password</th> -->
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                                {% for i in cameradetail %}
                                                <tr class="spacer"></tr>
                                                <tr class="tr-shadow">
                                                    <td>
                                                        <label class="au-checkbox">
                                                            <input type="checkbox">
                                                            <span class="au-checkmark"></span>
                                                        </label>
                                                    </td>
                                                <td>{{ i.name }}</td>
                                                <td>
                                                    <span class="status--process">{{ i.ip }}</span>
                                                <!-- </td>
                                                <td class="block-password">{{ i.auth_uname }}</td>
                                                <td class="block-password">{{ i.auth_pwd }}</td> -->

                                                <!-- <td>
                                                    <span class="status--process">Processed</span>
                                                </td>
                                                <td>$699.00</td> -->
                                                <!-- <td> -->
                                                    <!-- <div class="table-data-feature">
                                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Send">
                                                            <i class="zmdi zmdi-mail-send"></i>
                                                        </button>
                                                        <button class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                                            <i class="zmdi zmdi-edit"></i>
                                                        </button>
                                                        <button action="{% url 'Index:deletecamera' %}"class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                                            <i class="zmdi zmdi-delete"></i>
                                                        </button>
                                                        <button class="item" data-toggle="tooltip" data-placement="top" title="More">
                                                            <i class="zmdi zmdi-more"></i>
                                                        </button>
                                                    </div> -->
                                                </td>
                                            </tr>
                                        </tbody>
                                         {% endfor %}
                                    </table>
                                </div>



         </div>
         </div>
      </div>

{% endif %}
{% endblock %}

Index/templates/Index/cameralocation.html
{% extends "base.html" %}

{% block location %}
    {% if user.is_authenticated %}
  <li><a href="{% url 'home' %}" >Home</a> </li>
  <li><a href="{% url 'addcamera' %}">AddCamera</a></li>
  <li><a href="{% url 'deletecamera' %}">DeleteCamera</a></li>
  <li><a href="{% url 'cameras_list' %}">LIVE VIEW</a></li>
  <li><a href="#">Notification</a></li>
  <li><a href="{% url 'logout' %}">logout</a></li>

{% else %}

  <li><a href="{% url 'login' %}">login</a></li>
{% endif %}
{% endblock %}


{% block content %}
	{% for cam in CameraLists %}

        <img  src="{% url 'video_streamer' camID=cam.id  %}" width="300px" height="300px"/>
        <p> {{ cam.name }}</p>

    {% endfor %}

{% endblock %}

Index/templates/Index/cameras.html
{% extends "base.html" %}
{% load static %}
{% block location %}
{% if user.is_authenticated %}
<div class="row">

   {% for cam in CameraLists %}
   <div class="col-lg-6">
     <section class="card">
      <div class="card-body text-secondary" style="background-color:red"><img src="{% url 'Index:video_streamer' camID=cam.id  %}" /></div>
    </section>
      </div>
   {% endfor %}

</div>
  <!-- Main -->
  <!-- Copyright -->

{% else %}

      <li><a href="{% url 'Index:profile' %}" >register</a></li>
      <li><a href="{% url 'login' %}" >login</a></li>

{% endif %}
{% endblock %}

Index/templates/Index/home.html
{% extends "base.html"%}


{% block location %}
{% for location in locations %}

  {% endfor %}
{% endblock %}

{% block content %}


<h1>  Introductions </h1>

 <p>
            
              
               2.  Second go to <a href="{% url  'addcamera' %}">Camera</a> to input IP of the camera you use and specify the name of it,
                 select the Location you want to put and Choose the Function of the camera you want (or both)
               
            </p>
{% endblock %}

Index/templates/Index/image.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>AIBSSS</title>
  </head>
  <body>
    <img  src="{% static "Index/person3.jpg" %}" width="500px" height="500px"/>
  </body>
</html>

Index/templates/Index/notification.html
{% extends "base.html" %}
{% block location %}
{% if user.is_authenticated %}
{% load static %}




                  <div class="col-lg-12">
                      <div class="au-card au-card--no-shadow au-card--no-pad m-b-40">
                          <div class="au-card-title" style="background-image:url('images/bg-title-01.jpg');">
                              <div class="bg-overlay bg-overlay--blue"></div>
                              <h3>
                                  <i class="zmdi zmdi-account-calendar"></i>Notification</h3>

                          </div>
                          <div class="au-task js-list-load">

                              <div class="au-task-list js-scrollbar3">
                                {% for notify in noti %}
                                  <div class="au-task__item au-task__item--warning">
                                      <div class="au-task__item-inner">
                                        <div class="avatar-wrap ">
                                            <div class="avatar">
                                                <img src="{% static 'images/user-male-icon.png'%}" alt="Michelle Sims">
                                            </div>
                                        </div>
                                        <div class="avatar-wrap online">
                                            <!-- <div class="avatar"> -->
                                                <h1><i class="fa fa-film"></i></h1>
                                            <!-- </div> -->
                                        </div>

                                          <h5 class="task">
                                              <a href="#">{{ notify.place }}</a>
                                          </h5>
                                          <span class="time">{{ notify.time }}</span>
                                      </div>
                                  </div>
                                  {% endfor %}




                              </div>
                              <div class="au-task__footer">
                                  
                              </div>
                          </div>
                      </div>
                  </div>

  <!-- Copyright -->

{% else %}


      <li><a href="{% url 'login' %}">Continue</a></li>

{% endif %}
{% endblock %}

{% block content %}

 <!-- <form class="second3" action="" method="POST">
                {% csrf_token %}
                IP Camera :<br>
                <input type="text" name="ip" style="color:green;" ><br><br>
                Camera Name : <br>
                <input type="text" name="name" style="margin-top:6px;" ><br><br>
                username :<br>
                <input type="text" name="auth_uname" style="color:green;" ><br><br>
                 password :<br>
                <input type="password" name="auth_pwd" style="color:green;" ><br><br>
                <br><br><br>

                Choose Function:<br>
                <input type="checkbox" value="0" name="option[]">Face Recognition<br>
                <input type="checkbox" value="1" name="option[]">Object Detection<br><br>

                <input type="submit" name="submit" value="OK" style="align-content: center;">
            </form> -->

{% endblock %}

Index/templates/Index/profile.html
{% extends "base.html" %}
{% block location %}
{% if user.is_authenticated %}
<div class="col-lg-12">
    <div class="card">
      <div class="card-header">User Profile</div>
          <div class="card-body card-block">
               <form action="#" method="post" class="">
                 {% csrf_token %}
                 <div class="row form-group">
                     <div class="col col-md-3">
                         <label for="disabled-input" class=" form-control-label">Full Name</label>
                     </div>
                     <div class="col-12 col-md-9">
                         <input type="text" id="disabled-input" name="disabled-input" placeholder="{{ user.profile.fullname }}" disabled="" class="form-control">
                     </div>
                 </div>
                 <div class="row form-group">
                     <div class="col col-md-3">
                         <label for="disabled-input" class=" form-control-label">Location</label>
                     </div>
                     <div class="col-12 col-md-9">
                         <input type="text" id="disabled-input" name="disabled-input" placeholder="{{ user.profile.location }}" disabled="" class="form-control">
                     </div>
                 </div>
                 <div class="row form-group">
                     <div class="col col-md-3">
                         <label for="disabled-input" class=" form-control-label">DOB</label>
                     </div>
                     <div class="col-12 col-md-9">
                         <input type="text" id="disabled-input" name="disabled-input" placeholder="{{ user.profile.birth_date }}" disabled="" class="form-control">
                     </div>
                 </div>
                 <div class="row form-group">
                     <div class="col col-md-3">
                         <label for="disabled-input" class=" form-control-label">Phone NO</label>
                     </div>
                     <div class="col-12 col-md-9">
                         <input type="text" id="disabled-input" name="disabled-input" placeholder="{{ user.profile.phone }}" disabled="" class="form-control">
                     </div>
                 </div>
                 <div class="row form-group">
                     <div class="col col-md-3">
                         <label for="disabled-input" class=" form-control-label">Email ID</label>
                     </div>
                     <div class="col-12 col-md-9">
                         <input type="text" id="disabled-input" name="disabled-input" placeholder="{{ user.profile.email }}" disabled="" class="form-control">
                     </div>
                 </div>
                </form>
                <a class="btn btn-warning btn-lg btn-block" href="{% url 'Index:profileupdate' pk=user.profile.pk %}"> update</a>
          </div>
      </div>
</div>
{% endif %}
{% endblock %}

Index/templates/Index/register.html
{% extends "base.html" %}
{% block location %}
{% if user.is_authenticated %}
{% load static %}

<div class="col-lg-6">
    <div class="card">
    
<a class="btn btn-warning btn-lg btn-block" href="{% url 'Index:profileupdate' pk=user.profile.pk %}"> update</a>
   </div>
</div>

{% else %}

      <li><a href="{% url 'Index:profile' %}" >register</a></li>
      <li><a href="{% url 'login' %}" >login</a></li>

{% endif %}
{% endblock %}

Index/templates/Index/sample11.html
{% extends "base.html" %}
{% block location %}

<div id="wrapper">

  <!-- Header -->
    <header id="header">
    </header>

  <!-- Nav -->
    <nav id="nav">
      <ul class="links">
        <li ><a href="index.html">Home</a></li>
        <li ><a href="{% url 'cameras_list' %}">Live View</a></li>
        <li ><a href="{% url 'notification' %}">Notifications</a></li>
      </ul>
      <ul class="icons">
        <li><a href="{% url 'cameras_list' %}" class="icon fa-instagram"><span class="label">Twitter</span></a></li>
        <li><a href="{% url 'addcamera' %}" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="{% url 'deletecamera' %}" class="icon fa-facebook"><span class="label">Facebook</span></a></li>

      </ul>
    </nav>

  <!-- Main -->
    <div id="main">

          <!-- Form -->
            <h2>notification</h2>
            <form method="post" action="#">
               {% csrf_token %}
              <div class="row gtr-uniform">
                <!-- <div class="col-12">
                  <input type="text" name="name" placeholder="Camera Name" />
                </div>
                <div class="col-12">
                  <input type="text" name="ip" placeholder="Camera URL" />
                </div>
                <div class="col-12">
                  <input type="text" name="auth_uname"  placeholder="Username" />
                </div>
                <div class="col-12">
                  <input type="password" name="auth_pwd"  placeholder="Password" />
                </div> -->
                <div class="col-12">
                  <ul class="actions">
                    <li><input type="submit" value="send notification" class="primary" /></li>
                  </ul>
                </div>
              </div>
            </form>





  <!-- Copyright -->
    <div id="copyright">
      <ul><li>&copy; Untitled</li><li>Design: <a href="https://html5up.net">HTML5 UP</a></li></ul>
    </div>

</div>

{% endblock %}

{% block content %}

 <!-- <form class="second3" action="" method="POST">
                {% csrf_token %}
                IP Camera :<br>
                <input type="text" name="ip" style="color:green;" ><br><br>
                Camera Name : <br>
                <input type="text" name="name" style="margin-top:6px;" ><br><br>
                username :<br>
                <input type="text" name="auth_uname" style="color:green;" ><br><br>
                 password :<br>
                <input type="password" name="auth_pwd" style="color:green;" ><br><br>
                <br><br><br>

                Choose Function:<br>
                <input type="checkbox" value="0" name="option[]">Face Recognition<br>
                <input type="checkbox" value="1" name="option[]">Object Detection<br><br>

                <input type="submit" name="submit" value="OK" style="align-content: center;">
            </form> -->

{% endblock %}