Index/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='Index'
urlpatterns = [
 	url(r'^addcamera/',views.AddcameraView.as_view(), name='addcamera'),
 	url(r'^video_streamer/(?P<camID>\d+)',views.video_streamer, name='video_streamer'),
    url(r'^video_streamer1/',views.video_streamer1, name='video_streamer1'),
 	url(r'^cameras/',views.cameras_list, name='cameras_list'),
 	url(r'^deletecamera/',views.deletecamera, name='deletecamera'),
    url(r'^notification/',views.notification, name='notification'),
    url(r'^image/',views.image, name='image'),
    url(r'^cameradetails/',views.cameradetails, name='cameradetails'),
    url(r'^profile/',views.ProfileView.as_view(), name='profile'),
    url(r'^profile1/',views.ProfileView1.as_view(), name='profile1'),
    url(r'^profiledetail/(?P<pk>\d+)/$',views.ProfileDetailView.as_view(), name='profiledetail'),
    url(r'^profileupdate/(?P<pk>\d+)/$',views.ProfileUpdateView.as_view(), name='profileupdate'),
    # url(r'^jump/',views.jump, name='jump'),
    #url(r'^sample/',views.sample11, name='sample11'),
    url(r'^home/',views.home, name='home'),
    url(r'^preview/',views.preview, name='preview'),

    # AddcameraView.as_view()

 ]# + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from Index.views import (AddcameraView, LiveView)

urlpatterns = [
    url('admin/', admin.site.urls),
    url('api/v1/', include('Index.api_urls')),
    url(r'', include('Index.urls')),
    url(r'', include('faces.urls')),
    url('accounts/', include('django.contrib.auth.urls')),
    url('', TemplateView.as_view(template_name='home.html'), name='home'),#registration/login.html
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
'''
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Index.urls')),
]
'''

Index/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
#from accounts.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import time
from phonenumber_field.modelfields import PhoneNumberField

phonenumber = PhoneNumberField(blank=True)

# class Userprofile(models.Model):
# 	user = models.OneToOneField(User,on_delete=models.CASCADE)
# 	phone = models.IntegerField()
#
# 	def __str__(self):
# 		return self.phone


class Camera(models.Model):
	ip = models.CharField(max_length=500,null=False,blank=False,unique=True)
	name = models.CharField(max_length=500,null=False,blank=False)
	user = models.ForeignKey(User,null=True,on_delete=models.CASCADE)
	#option = models.CharField(max_length=20)
	#auth_uname = models.CharField(max_length=200)
	#uth_pwd = models.CharField(max_length=500)
	created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
	created_at = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.name



class Notification(models.Model):
	user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)
	name = models.CharField(max_length=50)
	place = models.CharField(max_length=50)
	time = models.CharField(max_length=50)

	def __str__(self):
		return self.name
def profile_image(user, filename):
    return "userpics/%s/%s" %(str(user)+str(int(time.time())),filename)

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	fullname = models.CharField(max_length=30)
	MALE = 'MA'
	FEMALE = 'FE'
	GENDERS_IN_PROJECT = (
	(MALE, 'male'),
	(FEMALE, 'female'),
	)
	location = models.CharField(max_length=30, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	gender = models.CharField(max_length=2,choices=GENDERS_IN_PROJECT,default=MALE)
	phone = PhoneNumberField(default=0,blank=True,null=True)
	email = models.EmailField(max_length=50,blank=True)
	image = models.ImageField(upload_to=profile_image,blank=True)
	image.allow_tags = True

	def __str__(self):
		return self.fullname

	def get_absolute_url(self):
		return reverse('Index:profiledetail',kwargs={'pk':self.pk})

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

templates/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Login</title>

    <!-- Fontfaces CSS-->
    <link href="{% static 'css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static  'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static  'vendor/font-awesome-5/css/fontawesome-all.min.css' %}"  rel="stylesheet" media="all">
    <link href="{% static  'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="{% static 'images/icon/logo.png' %}" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">
                            <form action="{% url 'Index:home'%}" method="post">
                              {% csrf_token %}
                                <div class="form-group">
                                    <label>User ID</label>
                                    <input class="au-input au-input--full" type="text" name="username" placeholder="UserID" autofocus required id="id_username">
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input class="au-input au-input--full" type="password" name="password" placeholder="Password" required id="id_password">
                                </div>
                                <div class="login-checkbox">
                                    <label>
                                        <input type="checkbox" name="remember">Remember Me
                                    </label>

                                    <!-- <label>
                                        <a href="#">Forgotten Password?</a>
                                    </label> -->
                                </div>
                                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">sign in</button>

                            </form>
                            <div class="register-link">
                                <p>
                                    Are you interested in AIBSSS?
                                    <a href="#">Enquiry Us</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% block location %}
    {% endblock %}
    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- Vendor JS       -->
    <script src="{% static 'vendor/slick/slick.min.js' %}">
    </script>
    <script src="{% static 'vendor/wow/wow.min.js'%}"></script>
    <script src="{% static 'vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
    </script>
    <script src="{% static 'vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'vendor/counter-up/jquery.counterup.min.js' %}">
    </script>
    <script src="{% static 'vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}">
    </script>

    <!-- Main JS-->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>
<!-- end document-->

templates/registration.html
{% extends "base.html" %}
{% block location %}
{% if user.is_authenticated %}
{% load static %}
<!-- <html lang="en">
<head> -->
    <!-- Required meta tags-->
    <!-- <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template"> -->

    <!-- Title Page-->

    <!-- Fontfaces CSS-->
    <!-- <link href="{% static 'css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static  'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static  'vendor/font-awesome-5/css/fontawesome-all.min.css' %}"  rel="stylesheet" media="all">
    <link href="{% static  'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all"> -->

    <!-- Bootstrap CSS-->
    <!-- <link href="{% static 'vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all"> -->

    <!-- Vendor CSS-->
    <!-- <link href="{% static 'vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all"> -->

    <!-- Main CSS-->
    <!-- <link href="{% static 'css/theme.css' %}" rel="stylesheet" media="all">

</head> -->

<!-- <body class="animsition">
  <div class="page-wrapper">
<div class="main-content">
      <div class="section__content section__content--p30">
          <div class="container-fluid">
              <div class="row"> -->
<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <strong>Update Profile</strong>
        </div>
        <div class="card-body card-block">
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
              {% csrf_token %}

                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_fullname" class=" form-control-label">Full Name:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="text" id="id_fullname" name="fullname" value="{{ user.profile.fullname }}" maxlength="30" placeholder="Enter Full Name" class="form-control">
                       <small class="form-text text-muted">Enter your Full name</small>
                   </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_location" class=" form-control-label">Location:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="text" id="id_location" name="location" value="{{ user.profile.location }}" maxlength="30" placeholder="Enter Location" class="form-control">
                       <small class="form-text text-muted">Enter your Current City</small>
                   </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_birth_date" class=" form-control-label">DOB:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="date" id="id_birth_date" value="{{ user.profile.birth_date }}" name="birth_date" placeholder="DD-MM-YYYY" class="form-control">
                       <small class="form-text text-muted">Enter your Date Of Birth</small>
                   </div>
                </div>
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="id_gender" class=" form-control-label">Gender:</label>
                    </div>
                     <div class="col-12 col-md-9">
                        <select name="gender" id="id_gender" class="form-control">
                            <option value="0">Please select</option>
                            <option value="MA">MALE</option>
                            <option value="FE">FEMALE</option>
                        </select>
                    </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_email" class=" form-control-label">Email ID:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="email" id="id_email" value="{{ user.profile.email }}" name="email" placeholder="Enter Email ID" class="form-control">
                       <small class="form-text text-muted">Enter your email id</small>
                   </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_phone" class=" form-control-label">Phone NO:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="tel" id="id_phone" name="phone" value="{{ user.profile.phone }}" placeholder="Enter Phone number" value='+91'class="form-control">
                       <small class="form-text text-muted">Enter your Mobile Number</small>
                   </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_image" class=" form-control-label">Image:</label>
                      
                       <!-- <input type="checkbox" name="image-clear" id="image-clear_id">
                       <label for="image-clear_id">Clear</label><br>
                                            Change: -->
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="file" id="id_image" name="image" accept="image/*" class="form-control-file">
                   </div>
               </div>
               <!-- <div class="row form-group">
                  <div class="col col-md-3">
                      <label for="id_user" class=" form-control-label">UserName:</label>
                  </div>
                  <div class="col-12 col-md-9">
                      <input type="text" id="id_user" name="user" placeholder="Enter Username" class="form-control">
                      <small class="form-text text-muted">Enter your Username provided by admin</small>
                  </div>
               </div> -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset" class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endif %}
{% endblock %}
<!-- </div>
</div>
</div>
</div>
</div>


  <script src="{% static 'vendor/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap-4.1/popper.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>

  <script src="{% static 'vendor/slick/slick.min.js' %}">
  </script>
  <script src="{% static 'vendor/wow/wow.min.js'%}"></script>
  <script src="{% static 'vendor/animsition/animsition.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
  <script src="{% static 'vendor/counter-up/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'vendor/counter-up/jquery.counterup.min.js' %}"></script>
  <script src="{% static 'vendor/circle-progress/circle-progress.min.js' %}"></script>
  <script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
  <script src="{% static 'vendor/chartjs/Chart.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/select2/select2.min.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>

</body>

</html> -->




  <!-- Copyright -->

templates/registration1.html
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->

    <!-- Fontfaces CSS-->
    <link href="{% static 'css/font-face.css' %}" rel="stylesheet" media="all">
    <link href="{% static  'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static  'vendor/font-awesome-5/css/fontawesome-all.min.css' %}"  rel="stylesheet" media="all">
    <link href="{% static  'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
  <div class="page-wrapper">
<div class="main-content">
      <div class="section__content section__content--p30">
          <div class="container-fluid">
              <div class="row">
<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <strong>Registration</strong> Page
        </div>
        <div class="card-body card-block">
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
              {% csrf_token %}
              {{ form.as_p }}
<!--
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_fullname" class=" form-control-label">Full Name:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="text" id="id_fullname" name="fullname" maxlength="30" placeholder="Enter Full Name" class="form-control">
                       <small class="form-text text-muted">Enter your Full name</small>
                   </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_location" class=" form-control-label">Location:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="text" id="id_location" name="location" maxlength="30" placeholder="Enter Location" class="form-control">
                       <small class="form-text text-muted">Enter your Current City</small>
                   </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_birth_date" class=" form-control-label">DOB:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="date" id="id_birth_date" name="birth_date" placeholder="DD-MM-YYYY" class="form-control">
                       <small class="form-text text-muted">Enter your Date Of Birth</small>
                   </div>
                </div>
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="id_gender" class=" form-control-label">Gender:</label>
                    </div>
                     <div class="col-12 col-md-9">
                        <select name="gender" id="id_gender" class="form-control">
                            <option value="0">Please select</option>
                            <option value="MA">MALE</option>
                            <option value="FE">FEMALE</option>
                        </select>
                    </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_phone" class=" form-control-label">Phone NO:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="tel" id="id_phone" name="phone" placeholder="Enter Phone number" class="form-control">
                       <small class="form-text text-muted">Enter your Mobile Number</small>
                   </div>
                </div>
                <div class="row form-group">
                   <div class="col col-md-3">
                       <label for="id_image" class=" form-control-label">Image:</label>
                   </div>
                   <div class="col-12 col-md-9">
                       <input type="file" id="id_image" name="image" accept="image/*" class="form-control-file">
                   </div>
               </div>
               <div class="row form-group">
                  <div class="col col-md-3">
                      <label for="id_user" class=" form-control-label">UserName:</label>
                  </div>
                  <div class="col-12 col-md-9">
                      <input type="text" id="id_user" name="user" placeholder="Enter Username" class="form-control">
                      <small class="form-text text-muted">Enter your Username provided by admin</small>
                  </div>
               </div> -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset" class="btn btn-danger btn-sm">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </form>
        </div>

    </div>
</div>
</div>
</div>
</div>
</div>
</div>

  <!-- Main -->
  <script src="{% static 'vendor/jquery-3.2.1.min.js' %}"></script>
  <!-- Bootstrap JS-->
  <script src="{% static 'vendor/bootstrap-4.1/popper.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
  <!-- Vendor JS       -->
  <script src="{% static 'vendor/slick/slick.min.js' %}">
  </script>
  <script src="{% static 'vendor/wow/wow.min.js'%}"></script>
  <script src="{% static 'vendor/animsition/animsition.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
  <script src="{% static 'vendor/counter-up/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'vendor/counter-up/jquery.counterup.min.js' %}"></script>
  <script src="{% static 'vendor/circle-progress/circle-progress.min.js' %}"></script>
  <script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
  <script src="{% static 'vendor/chartjs/Chart.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/select2/select2.min.js' %}"></script>

  <!-- Main JS-->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>




  <!-- Copyright -->